import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { CustomTableComponent } from '../custom-table/custom-table.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, CustomTableComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'customTable';
  tableData = [
    {
      id: 1,
      name: 'Alice Johnson',
      email: 'alice.johnson@example.com',
      age: 28,
      country: 'USA',
      status: 'Active',
    },
    {
      id: 2,
      name: 'Bob Smith',
      email: 'bob.smith@example.com',
      age: 34,
      country: 'Canada',
      status: 'Inactive',
    },
    {
      id: 3,
      name: 'Charlie Brown',
      email: 'charlie.brown@example.com',
      age: 30,
      country: 'UK',
      status: 'Active',
    },
    {
      id: 4,
      name: 'Daisy Miller',
      email: 'daisy.miller@example.com',
      age: 25,
      country: 'Australia',
      status: 'Pending',
    },
    {
      id: 5,
      name: 'Eva Martin',
      email: 'eva.martin@example.com',
      age: 29,
      country: 'France',
      status: 'Inactive',
    },
    {
      id: 6,
      name: 'Frank Brown',
      email: 'frank.brown@example.com',
      age: 36,
      country: 'Germany',
      status: 'Active',
    },
    {
      id: 7,
      name: 'George Davis',
      email: 'george.davis@example.com',
      age: 25,
      country: 'China',
      status: 'Inactive',
    },
    {
      id: 8,
      name: 'Hannah White',
      email: 'hannah.white@example.com',
      age: 32,
      country: 'United Kingdom',
      status: 'Active',
    },
    {
      id: 9,
      name: 'Ian Taylor',
      email: 'ian.taylor@example.com',
      age: 39,
      country: 'Japan',
      status: 'Inactive',
    },
    {
      id: 10,
      name: 'Julia Wilson',
      email: 'julia.wilson@example.com',
      age: 27,
      country: 'Brazil',
      status: 'Active',
    },
    {
      id: 11,
      name: 'Kevin Hall',
      email: 'kevin.hall@example.com',
      age: 43,
      country: 'Russia',
      status: 'Inactive',
    },
    {
      id: 12,
      name: 'Lily Brooks',
      email: 'lily.brooks@example.com',
      age: 31,
      country: 'India',
      status: 'Active',
    },
    {
      id: 13,
      name: 'Matthew Jenkins',
      email: 'matthew.jenkins@example.com',
      age: 24,
      country: 'Italy',
      status: 'Inactive',
    },
    {
      id: 14,
      name: 'Nicole Walker',
      email: 'nicole.walker@example.com',
      age: 35,
      country: 'Mexico',
      status: 'Active',
    },
    {
      id: 15,
      name: 'Olivia Lee',
      email: 'olivia.lee@example.com',
      age: 30,
      country: 'Spain',
      status: 'Inactive',
    },
    {
      id: 16,
      name: 'Peter Martin',
      email: 'peter.martin@example.com',
      age: 38,
      country: 'Australia',
      status: 'Active',
    },
    {
      id: 17,
      name: 'Rebecca Jones',
      email: 'rebecca.jones@example.com',
      age: 26,
      country: 'South Africa',
      status: 'Inactive',
    },
    {
      id: 18,
      name: 'Sarah Davis',
      email: 'sarah.davis@example.com',
      age: 33,
      country: 'Turkey',
      status: 'Active',
    },
    {
      id: 19,
      name: 'Thomas White',
      email: 'thomas.white@example.com',
      age: 42,
      country: 'Thailand',
      status: 'Inactive',
    },
    {
      id: 20,
      name: 'Uma Patel',
      email: 'uma.patel@example.com',
      age: 29,
      country: 'Vietnam',
      status: 'Active',
    },
    {
      id: 21,
      name: 'Vincent Brown',
      email: 'vincent.brown@example.com',
      age: 37,
      country: 'Poland',
      status: 'Inactive',
    },
    {
      id: 22,
      name: 'Walter Lee',
      email: 'walter.lee@example.com',
      age: 25,
      country: 'Sweden',
      status: 'Active',
    },
    {
      id: 23,
      name: 'Xavier Martin',
      email: 'xavier.martin@example.com',
      age: 32,
      country: 'Norway',
      status: 'Inactive',
    },
    {
      id: 24,
      name: 'Yvonne Taylor',
      email: 'yvonne.taylor@example.com',
      age: 39,
      country: 'Denmark',
      status: 'Active',
    },
    {
      id: 25,
      name: 'Zachary Wilson',
      email: 'zachary.wilson@example.com',
      age: 27,
      country: 'Finland',
      status: 'Inactive',
    },
    {
      id: 26,
      name: 'Abigail Brooks',
      email: 'abigail.brooks@example.com',
      age: 43,
      country: 'Greece',
      status: 'Active',
    },
    {
      id: 27,
      name: 'Benjamin Jenkins',
      email: 'benjamin.jenkins@example.com',
      age: 31,
      country: 'Portugal',
      status: 'Inactive',
    },
    {
      id: 28,
      name: 'Catherine Walker',
      email: 'catherine.walker@example.com',
      age: 36,
      country: 'Switzerland',
      status: 'Active',
    },
    {
      id: 29,
      name: 'Dominic Lee',
      email: 'dominic.lee@example.com',
      age: 30,
      country: 'Austria',
      status: 'Inactive',
    },
    {
      id: 30,
      name: 'Eleanor Martin',
      email: 'eleanor.martin@example.com',
      age: 33,
      country: 'Romania',
      status: 'Active',
    },
    {
      id: 31,
      name: 'Florence Jones',
      email: 'florence.jones@example.com',
      age: 42,
      country: 'Czech Republic',
      status: 'Inactive',
    },
    {
      id: 32,
      name: 'Gabriel Davis',
      email: 'gabriel.davis@example.com',
      age: 25,
      country: 'Hungary',
      status: 'Active',
    },
    {
      id: 33,
      name: 'Helen White',
      email: 'helen.white@example.com',
      age: 39,
      country: 'Belgium',
      status: 'Inactive',
    },
    {
      id: 34,
      name: 'Isabella Taylor',
      email: 'isabella.taylor@example.com',
      age: 27,
      country: 'Netherlands',
      status: 'Active',
    },
    {
      id: 35,
      name: 'Julian Wilson',
      email: 'julian.wilson@example.com',
      age: 32,
      country: 'Ireland',
      status: 'Inactive',
    },
    {
      id: 36,
      name: 'Katherine Brooks',
      email: 'katherine.brooks@example.com',
      age: 43,
      country: 'Israel',
      status: 'Active',
    },
    {
      id: 37,
      name: 'Luke Jenkins',
      email: 'luke.jenkins@example.com',
      age: 31,
      country: 'Singapore',
      status: 'Inactive',
    },
    {
      id: 38,
      name: 'Margaret Walker',
      email: 'margaret.walker@example.com',
      age: 36,
      country: 'Malaysia',
      status: 'Active',
    },
    {
      id: 39,
      name: 'Nathan Lee',
      email: 'nathan.lee@example.com',
      age: 30,
      country: 'Philippines',
      status: 'Inactive',
    },
    {
      id: 40,
      name: 'Olivia Martin',
      email: 'olivia.martin@example.com',
      age: 33,
      country: 'Indonesia',
      status: 'Active',
    },
    {
      id: 41,
      name: 'Patrick Jones',
      email: 'patrick.jones@example.com',
      age: 42,
      country: 'Pakistan',
      status: 'Inactive',
    },
    {
      id: 42,
      name: 'Rachel Davis',
      email: 'rachel.davis@example.com',
      age: 25,
      country: 'Bangladesh',
      status: 'Active',
    },
    {
      id: 43,
      name: 'Sophia White',
      email: 'sophia.white@example.com',
      age: 39,
      country: 'Nigeria',
      status: 'Inactive',
    },
    {
      id: 44,
      name: 'Thomas Taylor',
      email: 'thomas.taylor@example.com',
      age: 27,
      country: 'Egypt',
      status: 'Active',
    },
    {
      id: 45,
      name: 'Ursula Wilson',
      email: 'ursula.wilson@example.com',
      age: 32,
      country: 'Vietnam',
      status: 'Inactive',
    },
    {
      id: 46,
      name: 'Vincent Brooks',
      email: 'vincent.brooks@example.com',
      age: 43,
      country: 'Morocco',
      status: 'Active',
    },
    {
      id: 47,
      name: 'Walter Jenkins',
      email: 'walter.jenkins@example.com',
      age: 31,
      country: 'Algeria',
      status: 'Inactive',
    },
    {
      id: 48,
      name: 'Xanthe Walker',
      email: 'xanthe.walker@example.com',
      age: 36,
      country: 'Sri Lanka',
      status: 'Active',
    },
    {
      id: 49,
      name: 'Yolanda Lee',
      email: 'yolanda.lee@example.com',
      age: 30,
      country: 'Uzbekistan',
      status: 'Inactive',
    },
    {
      id: 50,
      name: 'Zoe Martin',
      email: 'zoe.martin@example.com',
      age: 33,
      country: 'Myanmar',
      status: 'Active',
    },
  ];
  columnData = [
    {
      Header: 'ID',
      accessor: 'id',
      sortable: true,
      resizable: true,
      filterable: true,
      draggable: true,
      pinnable: true,
      hideable: true,
    },
    {
      Header: 'Name',
      accessor: 'name',
      editable: true,
      sortable: true,
      resizable: true,
      filterable: true,
      draggable: true,
      pinnable: true,
      hideable: true,
    },
    {
      Header: 'Email',
      accessor: 'email',
      editable: true,
      sortable: true,
      resizable: true,
      filterable: true,
      draggable: true,
      pinnable: true,
      hideable: true,
    },
    {
      Header: 'Age',
      accessor: 'age',
      editable: true,
      sortable: true,
      resizable: true,
      filterable: true,
      draggable: true,
      pinnable: true,
      hideable: true,
    },
    {
      Header: 'Country',
      accessor: 'country',
      sortable: true,
      resizable: true,
      filterable: true,
      draggable: true,
      pinnable: true,
      hideable: true,
    },
    {
      Header: 'Status',
      accessor: 'status',
      editable: true,
      sortable: true,
      resizable: true,
      filterable: true,
      draggable: true,
      pinnable: true,
      hideable: true,
    },
  ];
}
